Path.delete_all
Path.reset_pk_sequence
Path.create!([
  {title_jp: "機関", title_en: "Institution master", model_name_field: "Kikanmst", path_url: "/kikanmsts?locale=ja"},
  {title_jp: "場所区分マスタ", title_en: "Location classification master", model_name_field: "Bashokubunmst", path_url: "/bashokubunmsts?locale=en"},
  {title_jp: "駅マスタ", title_en: "Station master", model_name_field: "Eki", path_url: "/ekis?locale=en"},
  {title_jp: "承認者マスタ", title_en: "Approver master", model_name_field: "Shoninshamst", path_url: "/shoninshamsts?locale=en"},
  {title_jp: "所属マスタ", title_en: "Affiliation master", model_name_field: "Shozokumaster", path_url: "/shozokumasters?locale=en"},
  {title_jp: "ロールマスタ", title_en: "Role master", model_name_field: "Rorumaster", path_url: "/rorumasters?locale=en"},
  {title_jp: "会社マスタ", title_en: "Company master", model_name_field: "Kaishamaster", path_url: "/kaishamasters?locale=en"},
  {title_jp: "ロールメンバ", title_en: "Role Member", model_name_field: "Rorumenba", path_url: "/rorumenbas?locale=en"},
  {title_jp: "設備マスタ", title_en: "Device master", model_name_field: "Setsubi", path_url: "/setsubis?locale=en"},
  {title_jp: "ジュピター休日", title_en: "Jupiter Holiday", model_name_field: "JptHolidayMst", path_url: "/jpt_holiday_msts?locale=en"},
  {title_jp: "有給休暇履歴", title_en: "", model_name_field: "YuukyuuKyuukaRireki", path_url: "/yuukyuu_kyuuka_rirekis?locale=en"},
  {title_jp: "役職マスタ", title_en: "Official position master", model_name_field: "Yakushokumaster", path_url: "/yakushokumasters?locale=en"},
  {title_jp: "設定", title_en: "Setting", model_name_field: "Setting", path_url: "/settings?locale=en"},
  {title_jp: "通信制御マスタ", title_en: "Communication control master", model_name_field: "Tsushinseigyou", path_url: "/tsushinseigyous?locale=en"},
  {title_jp: "経費入力管理", title_en: "Expenses", model_name_field: "Keihihead", path_url: "/keihiheads?locale=en"},
  {title_jp: "カラーマスタ", title_en: "Priority", model_name_field: "Yuusen", path_url: "/yuusens?locale=en"},
  {title_jp: "伝言用件マスタ", title_en: "Message requirement master", model_name_field: "Dengonyouken", path_url: "/dengonyoukens?locale=en"},
  {title_jp: "伝言回答マスタ", title_en: "Message reply master", model_name_field: "Dengonkaitou", path_url: "/dengonkaitous?locale=en"},
  {title_jp: "所在マスタ", title_en: "Location state master", model_name_field: "Shozai", path_url: "/shozais?locale=en"},
  {title_jp: "分類マスタ", title_en: "Classification master", model_name_field: "Bunrui", path_url: "/bunruis?locale=en"},
  {title_jp: "回覧用件マスタ", title_en: "Circulation master", model_name_field: "Kairanyokenmst", path_url: "/kairanyokenmsts?locale=en"},
  {title_jp: "場所マスタ", title_en: "Location master", model_name_field: "Bashomaster", path_url: "/bashomasters?locale=en"},
  {title_jp: "担当者マスタ", title_en: "Contact person master", model_name_field: "User", path_url: "/users?locale=en"},
  {title_jp: "カレンダー", title_en: "Calendar", model_name_field: "Event", path_url: "/events?locale=ja"},
  {title_jp: "工程マスタ", title_en: "Process master", model_name_field: "Kouteimaster", path_url: "/kouteimasters?locale=en"},
  {title_jp: "回覧", title_en: "Circulation", model_name_field: "Kairan", path_url: "/kairans?locale=en"},
  {title_jp: "状態マスタ", title_en: "State master", model_name_field: "Joutaimaster", path_url: "/joutaimasters?locale=en"},
  {title_jp: "社員マスタ", title_en: "Employee master", model_name_field: "Shainmaster", path_url: "/shainmasters?locale=en"},
  {title_jp: "タイムライン", title_en: "Timeline", model_name_field: "Event", path_url: "/events/time_line_view?locale=ja"},
  {title_jp: "JOBマスタ", title_en: "Job master", model_name_field: "Jobmaster", path_url: "/jobmasters?locale=en"},
  {title_jp: "設備予約", title_en: "Device reservation", model_name_field: "Setsubiyoyaku", path_url: "/setsubiyoyakus?locale=en"},
  {title_jp: "勤怠", title_en: "Attendance", model_name_field: "Kintai", path_url: "/kintais?locale=en"},
  {title_jp: "伝言マスタ", title_en: "Message", model_name_field: "Dengon", path_url: "/dengons?locale=en"}
])